version: "3.8"
services:
  bootnode:
    image: "ethereum/client-go"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes: 
      - ./bootnode/keystore:/root/private-ethereum/keystore:rw
      - ./bootnode/data:/root/private-ethereum/geth:rw
      - ./init-script.sh:/root/init-script.sh
      - ./genesis.json:/root/genesis.json
    networks:
      - default
    entrypoint: /root/init-script.sh
    command: --datadir=/root/private-ethereum --networkid 69 -verbosity 3 --nodiscover
  minernode:
    image: "ethereum/client-go"
    ports:
      - "30304:30304"
      - "30304:30304/udp"
    volumes: 
      - ./minernode/keystore:/root/private-ethereum/keystore:rw
      - ./minernode/data:/root/private-ethereum/geth:rw
      - ./init-script.sh:/root/init-script.sh
      - ./genesis.json:/root/genesis.json
    networks:
    - default
    entrypoint: /root/init-script.sh
    command: --datadir=/root/private-ethereum --networkid 69 --port 30304 -verbosity 3  --nodiscover
  rpcnode:
    image: "ethereum/client-go"
    ports:
      - "30305:30305"
      - "30305:30305/udp"
      - "8545:8545"
      - "8546:8546"
    volumes: 
      - ./rpcnode/keystore:/root/private-ethereum/keystore:rw
      - ./rpcnode/data:/root/private-ethereum/geth:rw
      - ./init-script.sh:/root/init-script.sh
      - ./genesis.json:/root/genesis.json
    networks:
    - default
    entrypoint: /root/init-script.sh
    command: --datadir=/root/private-ethereum --networkid 69 --port 30305 --http --http.addr rpcnode --http.corsdomain '*' --http.api personal,eth,net,web3 -verbosity 3  --nodiscover
networks:
  default:
    external:
      name: privtnet